# Generated by Django 4.2.1 on 2023-09-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_contact_date_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_sent',
        ),
    ]
