# Generated by Django 4.2.1 on 2023-07-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('sender', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('detail', models.TextField()),
            ],
        ),
    ]
