# Generated by Django 4.2.1 on 2023-09-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_contact_date_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
