# Generated by Django 4.2.1 on 2023-09-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
